apiVersion: apps/v1
kind: Deployment
metadata:
  name: kudos-frontend
  labels:
    app: kudos-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kudos-frontend
  template:
    metadata:
      labels:
        app: kudos-frontend
    spec:
      containers:
        - name: kudos-frontend
          image: 036983629554.dkr.ecr.us-east-1.amazonaws.com/kudos-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests: 
              cpu: "100m"
              memory: "128Mi" 
            limits:
              cpu: "500m"
              memory: "512Mi"
