apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kudos-frontend
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: kudos.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kudos-frontend
                port:
                  number: 80
