apiVersion: v1
kind: Service
metadata:
  name: kudos-frontend
spec:
  type: NodePort
  selector:
    app: kudos-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
