apiVersion: v1
kind: Service
metadata:
  name: kudos-frontend
spec:
  type: LoadBalancer  # This creates an AWS load balancer for external access
  selector:
    app: kudos-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
